Repository Tudy-Project/TUDY, pull requests merged in 2022-05, with the labels that each got.

#11 Util 폴더 생성
  TUDY.xcodeproj/project.pbxproj
  TUDY/Util/Error/SignUpError.swift
  TUDY/Util/Extension/UIColor+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#12 홈 화면 레이아웃 기본 프레임 V2
  TUDY.xcodeproj/project.pbxproj
  TUDY/ViewController/HomeViewController.swift
  TUDY/ViewController/Post.swift
  TUDY/ViewController/PostListCell.swift
  TUDY/ViewController/TabBarViewController.swift
Labels: refactor

#13 [Feat] 검색창 레이아웃 잡기 with HomeVC
  .gitmessage.txt
  TUDY.xcodeproj/project.pbxproj
  TUDY/ViewController/HomeViewController.swift
  TUDY/ViewController/Search/SearchCollectionViewCell.swift
  TUDY/ViewController/Search/SearchTableViewCell.swift
  TUDY/ViewController/Search/SearchViewController.swift
  TUDY/ViewController/Search/TestViewController.swift
  TUDY/ViewController/Search/WorkThemeView.swift
  TUDY/ViewController/TabBarViewController.swift
Labels: feature

#22 Util 폴더 폰트 추가
  TUDY/Util/Extension/UIFont+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#21 [Fix] Conflict Error & 헤더뷰 완성, 관심직무 임시 레이아웃 완성
  TUDY.xcodeproj/project.pbxproj
  TUDY/ViewController/HomeViewController.swift
  TUDY/ViewController/PostListCell.swift
Labels: refactor, 🐼 상운

#20 앱, 탭바 Coordinator 적용
  TUDY.xcodeproj/project.pbxproj
  TUDY/Resource/SceneDelegate.swift
  TUDY/Util/Coordinator/AppCoordinator.swift
  TUDY/Util/Coordinator/CoordinatorFinishDelegate.swift
  TUDY/Util/Coordinator/CoordinatorType.swift
  TUDY/Util/Coordinator/Protocol/AppCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Protocol/CoordinatorProtocol.swift
  TUDY/ViewController/Chat/ChatViewController.swift
  TUDY/ViewController/Chat/Coordinator/ChatCoordinator.swift
  TUDY/ViewController/Chat/Coordinator/Protocol/ChatCoordinatorProtocol.swift
  TUDY/ViewController/Home/Coordinator/HomeCoordinator.swift
  TUDY/ViewController/Home/Coordinator/Protocol/HomeCoordinatorProtocol.swift
  TUDY/ViewController/TabBarPage.swift
  TUDY/ViewController/TabCoordinator.swift
  TUDY/ViewController/TabCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이

#24 [Feat] Coordinator 네비게이션바 수정 - #17
  TUDY/ViewController/Home/Coordinator/HomeCoordinator.swift
  TUDY/ViewController/HomeViewController.swift
  TUDY/ViewController/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#25 Coordinator 폴더 분리 / 생성 - #17
  TUDY.xcodeproj/project.pbxproj
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Common/AppCoordinator.swift
  TUDY/Util/Coordinator/Common/AppCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Common/CoordinatorFinishDelegate.swift
  TUDY/Util/Coordinator/Common/CoordinatorProtocol.swift
  TUDY/Util/Coordinator/Common/CoordinatorType.swift
  TUDY/Util/Coordinator/GroupChatList/GroupChatListCoordinator.swift
  TUDY/Util/Coordinator/GroupChatList/GroupChatListCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinatorProtocol.swift
  TUDY/Util/Coordinator/PrivateChatList/PrivateChatListCoordinator.swift
  TUDY/Util/Coordinator/PrivateChatList/PrivateChatListCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Search/SearchCoordinator.swift
  TUDY/Util/Coordinator/Search/SearchCoordinatorProtocol.swift
  TUDY/Util/Coordinator/SignUp/SignUpCoordinator.swift
  TUDY/Util/Coordinator/SignUp/SignUpCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabBarPage.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
  TUDY/Util/Coordinator/Tap/TabCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이

#27 로그인 회원가입 화면, 홈 - 로그인 임시 연결
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/appleLoginButton.imageset/Contents.json
  TUDY/Assets.xcassets/appleLoginButton.imageset/appleLoginButton.png
  TUDY/Assets.xcassets/appleLoginButton.imageset/appleLoginButton@2x.png
  TUDY/Assets.xcassets/appleLoginButton.imageset/appleLoginButton@3x.png
  TUDY/Assets.xcassets/kakaoLoginButton.imageset/Contents.json
  TUDY/Assets.xcassets/kakaoLoginButton.imageset/kakaoLoginButton.png
  TUDY/Assets.xcassets/kakaoLoginButton.imageset/kakaoLoginButton@2x.png
  TUDY/Assets.xcassets/kakaoLoginButton.imageset/kakaoLoginButton@3x.png
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetNameViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorDelegate.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
  TUDY/Util/Coordinator/Tap/TabCoordinatorProtocol.swift
  TUDY/Util/Extension/UIButton+Custom.swift
  TUDY/Util/Extension/UILabel+Custom.swift
  TUDY/Util/Extension/UITextField+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#29 [Chore] 리뷰사항 반영 및 일부 레이아웃 임시 변경
  TUDY/Assets.xcassets/magnifier.imageset/Contents.json
  TUDY/Assets.xcassets/magnifier.imageset/magnifier.png
  TUDY/Assets.xcassets/magnifier.imageset/magnifier@2x.png
  TUDY/Assets.xcassets/magnifier.imageset/magnifier@3x.png
  TUDY/Assets.xcassets/profile.imageset/Contents.json
  TUDY/Assets.xcassets/profile.imageset/profile.png
  TUDY/Assets.xcassets/profile.imageset/profile@2x.png
  TUDY/Assets.xcassets/profile.imageset/profile@3x.png
  TUDY/Models/Post.swift
  TUDY/Presentations/Home/View/PostListCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
Labels: chore, 🐼 상운

#30 로그인, 회원가입 화면 이동 및 UI업데이트
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetNameViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinatorProtocol.swift
  TUDY/Util/Coordinator/SignUp/SignUpCoordinator.swift
  TUDY/Util/Coordinator/SignUp/SignUpCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
  TUDY/Util/Extension/UIButton+Custom.swift
  TUDY/Util/Extension/UITextField+Custom.swift
  TUDY/Util/Extension/UIToolbar+Custom.swift
Labels: feature, chore, 🐻‍❄️ 늘이

#32 [Feat] Font, Color 추가
  TUDY/Assets.xcassets/TUDYColor/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray1.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray2.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray3.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray4.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray5.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Dark-gray6.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray1.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray2.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray3.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray4.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray5.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/Light-gray6.colorset/Contents.json
  TUDY/Assets.xcassets/TUDYColor/White.colorset/Contents.json
  TUDY/Util/Extension/UIColor+Custom.swift
  TUDY/Util/Extension/UIFont+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#34 로그인, 회원가입 View 구현
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/TUDYColor/PointRed.colorset/Contents.json
  TUDY/Assets.xcassets/nameCheck.imageset/Contents.json
  TUDY/Assets.xcassets/nameCheck.imageset/nameCheck.png
  TUDY/Assets.xcassets/nameCheck.imageset/nameCheck@2x.png
  TUDY/Assets.xcassets/nameCheck.imageset/nameCheck@3x.png
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetNameViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Presentations/Signup/View/DetailJobButton.swift
  TUDY/Presentations/Signup/View/DetailJobCell.swift
  TUDY/Presentations/Signup/View/Job.swift
  TUDY/Presentations/Signup/View/JobButton.swift
  TUDY/Presentations/Signup/View/JobCell.swift
  TUDY/Presentations/Signup/View/Subway.swift
  TUDY/Presentations/Signup/View/SubwayListCell.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Extension/UIButton+Custom.swift
  TUDY/Util/Extension/UIColor+Custom.swift
  TUDY/Util/Extension/UIFont+Custom.swift
  TUDY/Util/Extension/UILabel+Custom.swift
  TUDY/Util/Extension/UITextField+Custom.swift
  TUDY/Util/Extension/UIToolbar+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#38 ProjectDetailViewController 연결 및 properties설정 + Conflict Fixed
  ProjectWrite/View/JobTableViewCell.swift
  ProjectWrite/View/ProjectDetailViewController.swift
  ProjectWrite/View/ProjectWriteTableViewCell.swift
  ProjectWriteViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Home/View/PostListCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Util/Extension/UIButton+Custom.swift
Labels: feature, chore, 🐼 상운
