Repository Tudy-Project/TUDY, pull requests merged in 2022-06, with the labels that each got.

#41 로그인 유무 판별 테스트
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
Labels: feature, 🐻‍❄️ 늘이

#46 [Feat] PHPicker 연결 및 리뷰사항 반영
  ProjectWrite/View/PhotoCell.swift
  ProjectWrite/View/RelatedJobCategoriesView.swift
  ProjectWriteViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Util/Extension/UIView+Custom.swift
Labels: feature, chore

#48 회원가입 시작하기 버튼 -> 홈화면으로 이동
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinatorDelegate.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#45 채팅 리스트 view 구현 (미완)
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/ChatList.swift
  TUDY/Models/ChatState.swift
  TUDY/Presentations/Chat/View/ChatListCell.swift
  TUDY/Presentations/Chat/ViewController/ChatListViewController.swift
  TUDY/Presentations/Chat/ViewController/ChatViewController.swift
  TUDY/Presentations/Signup/View/DetailJobCell.swift
  TUDY/Presentations/Signup/View/JobCell.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#49 탭바 아이콘 적용
  TUDY/Assets.xcassets/chat-selected.imageset/Contents.json
  TUDY/Assets.xcassets/chat-selected.imageset/chat-selected.png
  TUDY/Assets.xcassets/chat-selected.imageset/chat-selected@2x.png
  TUDY/Assets.xcassets/chat-selected.imageset/chat-selected@3x.png
  TUDY/Assets.xcassets/chat-unselected.imageset/Contents.json
  TUDY/Assets.xcassets/chat-unselected.imageset/chat-unselected.png
  TUDY/Assets.xcassets/chat-unselected.imageset/chat-unselected@2x.png
  TUDY/Assets.xcassets/chat-unselected.imageset/chat-unselected@3x.png
  TUDY/Assets.xcassets/home-selected.imageset/Contents.json
  TUDY/Assets.xcassets/home-selected.imageset/home-selected.png
  TUDY/Assets.xcassets/home-selected.imageset/home-selected@2x.png
  TUDY/Assets.xcassets/home-selected.imageset/home-selected@3x.png
  TUDY/Assets.xcassets/home-unselected.imageset/Contents.json
  TUDY/Assets.xcassets/home-unselected.imageset/home-unselected.png
  TUDY/Assets.xcassets/home-unselected.imageset/home-unselected@2x.png
  TUDY/Assets.xcassets/home-unselected.imageset/home-unselected@3x.png
  TUDY/Util/Coordinator/Tap/TabBarPage.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#53 회원가입시 User FireStore에 저장
  TUDY/Models/User.swift
  TUDY/Network/CommonFirebaseDatabaseNetworkService.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetNameViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
Labels: feature, 🐻‍❄️ 늘이

#56 [Feat] 검색창 CollectionView 레이아웃
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/cancelbutton_grey.imageset/Contents.json
  TUDY/Assets.xcassets/cancelbutton_grey.imageset/Group 267.png
  TUDY/Assets.xcassets/cancelbutton_grey.imageset/Group 267@2x.png
  TUDY/Assets.xcassets/cancelbutton_grey.imageset/Group 267@3x.png
  TUDY/Assets.xcassets/cancelbutton_white.imageset/Contents.json
  TUDY/Assets.xcassets/cancelbutton_white.imageset/Group 412.png
  TUDY/Assets.xcassets/cancelbutton_white.imageset/Group 412@2x.png
  TUDY/Assets.xcassets/cancelbutton_white.imageset/Group 412@3x.png
  TUDY/Assets.xcassets/mac_icon.imageset/Contents.json
  TUDY/Assets.xcassets/mac_icon.imageset/‍💻.png
  TUDY/Assets.xcassets/mac_icon.imageset/‍💻@2x.png
  TUDY/Assets.xcassets/mac_icon.imageset/‍💻@3x.png
  TUDY/Presentations/Home/View/WorkThemeView.swift
  TUDY/Presentations/Search/View/ResultCell.swift
  TUDY/Presentations/Search/View/WorkCell.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐶 호진

#60 채팅방 리스트 컴포넌트 구현, 스와이프 액션 구현
  ProjectWrite/CategoriesViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/chatPerson.imageset/Contents.json
  TUDY/Assets.xcassets/chatPerson.imageset/chatPerson.png
  TUDY/Assets.xcassets/chatPerson.imageset/chatPerson@2x.png
  TUDY/Assets.xcassets/chatPerson.imageset/chatPerson@3x.png
  TUDY/Models/ChatList.swift
  TUDY/Presentations/Chat/View/GroupChatListCell.swift
  TUDY/Presentations/Chat/View/PersonalChatListCell.swift
  TUDY/Presentations/Chat/View/TopBarCell.swift
  TUDY/Presentations/Chat/ViewController/ChatListViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Util/Extension/UIButton+Custom.swift
  TUDY/Util/Extension/UILabel+Custom.swift
  TUDY/Util/Extension/UIView+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#61 [Feat] 홈화면 새로 만들기 -#57
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Util/Extension/UIFont+Custom.swift
Labels: feature

#59 [Feat] SearchVC 하단 CollectionView 추가
  TUDY/Assets.xcassets/check_white.imageset/Contents.json
  TUDY/Assets.xcassets/check_white.imageset/Vector.png
  TUDY/Assets.xcassets/check_white.imageset/Vector@2x.png
  TUDY/Assets.xcassets/check_white.imageset/Vector@3x.png
  TUDY/Presentations/Search/View/ResultCell.swift
  TUDY/Presentations/Search/View/WorkCell.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
  TUDY/Util/Extension/UIColor+Custom.swift
  TUDY/Util/Extension/UIView+Custom.swift
Labels: feature, 🐶 호진

#65 🚒[긴급] ERROR FIX
  TUDY/Presentations/Search/View/WorkCell.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
Labels: bug

#68 [Fix] 회원가입 화면 진입 오류 수정
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
Labels: feature, 🐻‍❄️ 늘이

#70 [Feat] Add FirebaseFunction about Project -(#7)
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/Post.swift
  TUDY/Models/Project.swift
  TUDY/Network/CommonFirebaseDatabaseNetworkService.swift
  TUDY/Presentations/Home/View/PostListCell.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Repositories/CommonFirebaseProjectData.swift
  TUDY/Util/Extension/UIViewController+Custom.swift
Labels: feature, 🐶 호진

#71 채팅 코디네이터 연결 및 채팅 목록 파이어베이스 함수 생성
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/ChatInfo.swift
  TUDY/Models/ChatList.swift
  TUDY/Models/ChatState.swift
  TUDY/Presentations/Chat/ChatProtocol.swift
  TUDY/Presentations/Chat/View/GroupChatListCell.swift
  TUDY/Presentations/Chat/View/PersonalChatListCell.swift
  TUDY/Presentations/Chat/ViewController/ChatListViewController.swift
  TUDY/Presentations/Chat/ViewController/GroupChatViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Repositories/CommonFirebaseChat.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이

#72 [Feat] 홈화면 리팩토링 및 컬렉션뷰 추가 - #57
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/View/BottomSheetCollectionView.swift
  TUDY/Presentations/Home/View/FastSearchCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Util/Extension/UIViewController+Custom.swift
Labels: feature, 🐼 상운

#73 Job 구조체 변경 및 자잘한 수정
  TUDY/Models/Job.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetInterestedJobViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/View/JobButton.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinator.swift
  TUDY/Util/Coordinator/Login/LoginCoordinatorProtocol.swift
Labels: refactor, feature, 🐻‍❄️ 늘이

#75 [Feat] User 정보 가져오는 함수
  TUDY/Repositories/CommonFirebaseUserData.swift
Labels: feature, 🐻‍❄️ 늘이

#76 채팅방 리스트 레이아웃
  TUDY/Assets.xcassets/bell.cancel.imageset/Contents.json
  TUDY/Assets.xcassets/bell.cancel.imageset/bell.cancel.png
  TUDY/Assets.xcassets/bell.cancel.imageset/bell.cancel@2x.png
  TUDY/Assets.xcassets/bell.cancel.imageset/bell.cancel@3x.png
  TUDY/Assets.xcassets/bell.fill.imageset/Contents.json
  TUDY/Assets.xcassets/bell.fill.imageset/bell.fill.png
  TUDY/Assets.xcassets/bell.fill.imageset/bell.fill@2x.png
  TUDY/Assets.xcassets/bell.fill.imageset/bell.fill@3x.png
  TUDY/Assets.xcassets/pin.fill.imageset/Contents.json
  TUDY/Assets.xcassets/pin.fill.imageset/pin.fill.png
  TUDY/Assets.xcassets/pin.fill.imageset/pin.fill@2x.png
  TUDY/Assets.xcassets/pin.fill.imageset/pin.fill@3x.png
  TUDY/Assets.xcassets/pin.imageset/Contents.json
  TUDY/Assets.xcassets/pin.imageset/pin.png
  TUDY/Assets.xcassets/pin.imageset/pin@2x.png
  TUDY/Assets.xcassets/pin.imageset/pin@3x.png
  TUDY/Presentations/Chat/View/GroupChatListCell.swift
  TUDY/Presentations/Chat/View/PersonalChatListCell.swift
  TUDY/Presentations/Chat/ViewController/ChatListViewController.swift
  TUDY/Util/Extension/UIButton+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#78 [Chore] Conflict 해결 & 홈화면 디벨롭 1차
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/android_icon.imageset/Contents.json
  TUDY/Assets.xcassets/android_icon.imageset/android.png
  TUDY/Assets.xcassets/android_icon.imageset/android@2x.png
  TUDY/Assets.xcassets/android_icon.imageset/android@3x.png
  TUDY/Assets.xcassets/apple_icon.imageset/Contents.json
  TUDY/Assets.xcassets/apple_icon.imageset/apple_icon.png
  TUDY/Assets.xcassets/apple_icon.imageset/apple_icon@2x.png
  TUDY/Assets.xcassets/apple_icon.imageset/apple_icon@3x.png
  TUDY/Assets.xcassets/branding_icon.imageset/Contents.json
  TUDY/Assets.xcassets/branding_icon.imageset/branding_icon.png
  TUDY/Assets.xcassets/branding_icon.imageset/branding_icon@2x.png
  TUDY/Assets.xcassets/branding_icon.imageset/branding_icon@3x.png
  TUDY/Assets.xcassets/uxui_icon.imageset/Contents.json
  TUDY/Assets.xcassets/uxui_icon.imageset/uxui_icon.png
  TUDY/Assets.xcassets/uxui_icon.imageset/uxui_icon@2x.png
  TUDY/Assets.xcassets/uxui_icon.imageset/uxui_icon@3x.png
  TUDY/Assets.xcassets/‍‍design_icon.imageset/Contents.json
  TUDY/Assets.xcassets/‍‍design_icon.imageset/‍‍design_icon.png
  TUDY/Assets.xcassets/‍‍design_icon.imageset/‍‍design_icon@2x.png
  TUDY/Assets.xcassets/‍‍design_icon.imageset/‍‍design_icon@3x.png
  TUDY/Models/UserInfo.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
Labels: feature, chore, 🐼 상운

#81 [Feat] 홈화면 디벨롭 및 디테일 연결
  ProjectWrite/View/ProjectDetailViewController.swift
  ProjectWriteViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/View/FastSearchCell.swift
  TUDY/Presentations/Home/View/TestData.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Util/Extension/UIFont+Custom.swift
  TUDY/Util/Extension/UIViewController+Custom.swift
Labels: refactor, feature, 🐼 상운

#83 [Feat] 개인채팅방 bottom Sheet 작업
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/Project.swift
  TUDY/Models/User.swift
  TUDY/Presentations/Chat/View/PersonalBottomSheetTableViewCell.swift
  TUDY/Presentations/Chat/ViewController/GroupChatViewController.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
  TUDY/Util/Extension/Codable+Custom.swift
Labels: feature, 🐶 호진

#85 [Feat] 채팅 리스트 DB연결
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/ChatInfo.swift
  TUDY/Models/ChatState.swift
  TUDY/Models/Message.swift
  TUDY/Models/User.swift
  TUDY/Models/UserChatInfo.swift
  TUDY/Presentations/Chat/View/GroupChatListCell.swift
  TUDY/Presentations/Chat/View/PersonalChatListCell.swift
  TUDY/Presentations/Chat/ViewController/ChatListViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/WelcomeViewController.swift
  TUDY/Repositories/FirebaseChat.swift
  TUDY/Repositories/FirebaseProject.swift
  TUDY/Repositories/FirebaseUser.swift
  TUDY/Repositories/FirebaseUserChatInfo.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Common/LoginCheckDelegate.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorDelegate.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#87 [Feat] 프로젝트 디테일 레이아웃 기본 완성 -#86
  Podfile.lock
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY/Presentations/Home/View/TestData.swift
Labels: feature, 🐼 상운

#88 [Feat] Personal Chat Room Layout #1
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/sendmessage.imageset/Contents.json
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@1x.png
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@2x.png
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@3x.png
  TUDY/Presentations/Chat/View/ChatInputAccessoryView.swift
  TUDY/Presentations/Chat/View/PersonalBottomSheetTableViewCell.swift
  TUDY/Presentations/Chat/View/PersonalChatCollectionViewController.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Presentations/ChatList/View/GroupChatListCell.swift
  TUDY/Presentations/ChatList/View/PersonalChatListCell.swift
  TUDY/Presentations/ChatList/View/TopBarCell.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Util/Extension/UILabel+Custom.swift
Labels: feature, 🐶 호진

#90 chat DB
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY/Models/Message.swift
  TUDY/Presentations/ChatList/View/PersonalChatListCell.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Repositories/FirebaseChat.swift
  TUDY/Repositories/FirebaseRealtimeChat.swift
  TUDY/Repositories/FirebaseUser.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorDelegate.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#93 채팅방 나가기, 리스트 옵저버 등록
  TUDY/Models/Message.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Repositories/FirebaseChat.swift
  TUDY/Repositories/FirebaseRealtimeChat.swift
  TUDY/Repositories/FirebaseUserChatInfo.swift
Labels: feature, 🐻‍❄️ 늘이

#91 [Feat] 프로젝트 디테일 하트 버튼 애니메이션 및 아이콘 추가 변경
  ProjectDetail/View/HeartButton.swift
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/love.imageset/Contents.json
  TUDY/Assets.xcassets/love.imageset/love.png
  TUDY/Assets.xcassets/love.imageset/love@2x.png
  TUDY/Assets.xcassets/love.imageset/love@3x.png
  TUDY/Assets.xcassets/love_fill.imageset/Contents.json
  TUDY/Assets.xcassets/love_fill.imageset/love_fill.png
  TUDY/Assets.xcassets/love_fill.imageset/love_fill@2x.png
  TUDY/Assets.xcassets/love_fill.imageset/love_fill@3x.png
  TUDY/Assets.xcassets/more_vertical.imageset/Contents.json
  TUDY/Assets.xcassets/more_vertical.imageset/more_vertical.png
  TUDY/Assets.xcassets/more_vertical.imageset/more_vertical@2x.png
  TUDY/Assets.xcassets/more_vertical.imageset/more_vertical@3x.png
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@1x.png
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@2x.png
  TUDY/Assets.xcassets/sendmessage.imageset/문자보내기 1@3x.png
Labels: feature, 🐼 상운

#94 [Feat] 개인 채팅방 사진 및 채팅container추가 - (#82)
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/love.imageset/Contents.json
  TUDY/Assets.xcassets/love.imageset/sendmessage.png
  TUDY/Assets.xcassets/love.imageset/sendmessage@2x.png
  TUDY/Assets.xcassets/love.imageset/sendmessage@3x.png
  TUDY/Info.plist
  TUDY/Presentations/Chat/View/ChatInputAccessoryView.swift
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/View/PersonalChatCollectionViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
Labels: feature, 🐶 호진

#96 chatInfo 채팅방으로 넘기기 문법수정
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
Labels: feature, 🐻‍❄️ 늘이

#97 Date 변환함수 생성
  TUDY/Presentations/ChatList/View/GroupChatListCell.swift
  TUDY/Util/Extension/String+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#98 [Feat] Home에 UserInfo Singleton추가
  TUDY/Models/UserInfo.swift
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Repositories/FirebaseUser.swift
Labels: feature, 🐶 호진

#99 [Fix] addUserSnapShotLister 모든 상황에서 적용
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Repositories/FirebaseUser.swift
Labels: bug, 🐶 호진

#100 채팅리스트 레이아웃 변경, 즐겨찾기 삭제, Date 변경
  TUDY/Presentations/ChatList/View/GroupChatListCell.swift
  TUDY/Presentations/ChatList/View/PersonalChatListCell.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Util/Extension/Date+Custom.swift
  TUDY/Util/Extension/String+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#103 FireStorage Pod 추가
  Podfile
  Podfile.lock
  TUDY.xcodeproj/project.pbxproj
  TUDY/Repositories/FirebaseStorage.swift
Labels: feature, 🐻‍❄️ 늘이

#105 [Feat] Firebase project 연결 및 projectWrite 레이아웃 수정
  ProjectWrite/CategoriesViewController.swift
  ProjectWrite/ProjectConditionsViewController.swift
  ProjectWriteViewController.swift
  TUDY/Presentations/View/BottomSheetViewController.swift
  TUDY/Repositories/FirebaseProject.swift
Labels: feature, 🐼 상운

#106 채팅보내기 클릭시 개인채팅 뷰로 이동
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Repositories/FirebaseUser.swift
Labels: feature, 🐻‍❄️ 늘이

#107 이미지 저장, 불러오기
  Podfile
  Podfile.lock
  TUDY/Repositories/FirebaseStorage.swift
Labels: feature, 🐻‍❄️ 늘이

#110 [Feat] Message Fetch
  Podfile.lock
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/AppIcon.appiconset/100.png
  TUDY/Assets.xcassets/AppIcon.appiconset/1024.png
  TUDY/Assets.xcassets/AppIcon.appiconset/114.png
  TUDY/Assets.xcassets/AppIcon.appiconset/120.png
  TUDY/Assets.xcassets/AppIcon.appiconset/128.png
  TUDY/Assets.xcassets/AppIcon.appiconset/144.png
  TUDY/Assets.xcassets/AppIcon.appiconset/152.png
  TUDY/Assets.xcassets/AppIcon.appiconset/16.png
  TUDY/Assets.xcassets/AppIcon.appiconset/167.png
  TUDY/Assets.xcassets/AppIcon.appiconset/172.png
  TUDY/Assets.xcassets/AppIcon.appiconset/180.png
  TUDY/Assets.xcassets/AppIcon.appiconset/196.png
  TUDY/Assets.xcassets/AppIcon.appiconset/20.png
  TUDY/Assets.xcassets/AppIcon.appiconset/216.png
  TUDY/Assets.xcassets/AppIcon.appiconset/256.png
  TUDY/Assets.xcassets/AppIcon.appiconset/29.png
  TUDY/Assets.xcassets/AppIcon.appiconset/32.png
  TUDY/Assets.xcassets/AppIcon.appiconset/40.png
  TUDY/Assets.xcassets/AppIcon.appiconset/48.png
  TUDY/Assets.xcassets/AppIcon.appiconset/50.png
  TUDY/Assets.xcassets/AppIcon.appiconset/512.png
  TUDY/Assets.xcassets/AppIcon.appiconset/55.png
  TUDY/Assets.xcassets/AppIcon.appiconset/57.png
  TUDY/Assets.xcassets/AppIcon.appiconset/58.png
  TUDY/Assets.xcassets/AppIcon.appiconset/60.png
  TUDY/Assets.xcassets/AppIcon.appiconset/64.png
  TUDY/Assets.xcassets/AppIcon.appiconset/72.png
  TUDY/Assets.xcassets/AppIcon.appiconset/76.png
  TUDY/Assets.xcassets/AppIcon.appiconset/80.png
  TUDY/Assets.xcassets/AppIcon.appiconset/87.png
  TUDY/Assets.xcassets/AppIcon.appiconset/88.png
  TUDY/Assets.xcassets/AppIcon.appiconset/Contents.json
  TUDY/Presentations/Chat/View/ChatInputAccessoryView.swift
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/View/MessageHelper.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
Labels: feature, 🐶 호진

#109 홈화면, 프로젝트 디테일 레이아웃 구성 및 DB연결
  ProjectWrite/CategoriesViewController.swift
  ProjectWrite/ProjectConditionsViewController.swift
  ProjectWrite/View/DoubleSlider.swift
  ProjectWrite/View/OptionSelectionBar.swift
  ProjectWrite/View/ProjectDetailViewController.swift
  ProjectWriteViewController.swift
  TUDY/Models/Project.swift
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/View/FastSearchCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
  TUDY/Presentations/Search/View/ResultCell.swift
  TUDY/Presentations/Search/View/WorkCell.swift
  TUDY/Presentations/Search/ViewController/SearchViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetNameViewController.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Presentations/View/BottomSheetViewController.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorProtocol.swift
  TUDY/Util/Extension/UIButton+Custom.swift
  TUDY/Util/Extension/UIViewController+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#111 [긴급] HideKeyboard 수정
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
Labels: bug, chore, 🐶 호진

#113 [Feat] 개인챗 로직 변경
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Repositories/FirebaseUserChatInfo.swift
Labels: bug, feature, 🐶 호진

#112 홈화면, 디테일화면 작업
  ProjectDetail/ChatButtonEvent.swift
  ProjectDetail/View/HashtagCell.swift
  ProjectDetail/View/HeartButton.swift
  ProjectWrite/CategoriesViewController.swift
  ProjectWrite/View/DevelopCell.swift
  ProjectWrite/View/ProjectDetailViewController.swift
  ProjectWriteViewController.swift
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/ChatList/View/PersonalChatListCell.swift
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Repositories/FirebaseProject.swift
  TUDY/Repositories/FirebaseUser.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Extension/String+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#114 [Feat] Add ProjectDetailChat with projectMasterID
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
Labels: bug, feature, 🐶 호진

#115 Date 및 채팅 보내기 이동 오류 수정
  ProjectWriteViewController.swift
  TUDY/Presentations/Chat/ViewController/InvitedViewController.swift
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
  TUDY/Util/Extension/Date+Custom.swift
  TUDY/Util/Extension/String+Custom.swift
Labels: feature, 🐻‍❄️ 늘이

#116 기본 프로필 이미지 연동 및 프로젝트 이미지 연동
  ProjectWrite/View/ProjectDetailViewController.swift
  ProjectWriteViewController.swift
  TUDY/Assets.xcassets/defaultProfile.imageset/Contents.json
  TUDY/Assets.xcassets/defaultProfile.imageset/profile.png
  TUDY/Assets.xcassets/defaultProfile.imageset/profile@2x.png
  TUDY/Assets.xcassets/defaultProfile.imageset/profile@3x.png
  TUDY/Presentations/ChatList/View/PersonalChatListCell.swift
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
Labels: feature, 🐻‍❄️ 늘이

#117 Fix 개인채팅방 중복생성, 레이아웃 수정
  ProjectWrite/View/ProjectDetailViewController.swift
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Util/Extension/UIFont+Custom.swift
Labels: bug, 🐻‍❄️ 늘이

#120 [Feat] Message FireStore Changed -#82
  TUDY.xcodeproj/project.pbxproj
  TUDY/Assets.xcassets/AppIcon.appiconset/100.png
  TUDY/Assets.xcassets/AppIcon.appiconset/1024.png
  TUDY/Assets.xcassets/AppIcon.appiconset/114.png
  TUDY/Assets.xcassets/AppIcon.appiconset/120.png
  TUDY/Assets.xcassets/AppIcon.appiconset/128.png
  TUDY/Assets.xcassets/AppIcon.appiconset/144.png
  TUDY/Assets.xcassets/AppIcon.appiconset/152.png
  TUDY/Assets.xcassets/AppIcon.appiconset/16.png
  TUDY/Assets.xcassets/AppIcon.appiconset/167.png
  TUDY/Assets.xcassets/AppIcon.appiconset/172.png
  TUDY/Assets.xcassets/AppIcon.appiconset/180.png
  TUDY/Assets.xcassets/AppIcon.appiconset/196.png
  TUDY/Assets.xcassets/AppIcon.appiconset/20.png
  TUDY/Assets.xcassets/AppIcon.appiconset/216.png
  TUDY/Assets.xcassets/AppIcon.appiconset/256.png
  TUDY/Assets.xcassets/AppIcon.appiconset/29.png
  TUDY/Assets.xcassets/AppIcon.appiconset/32.png
  TUDY/Assets.xcassets/AppIcon.appiconset/40.png
  TUDY/Assets.xcassets/AppIcon.appiconset/48.png
  TUDY/Assets.xcassets/AppIcon.appiconset/50.png
  TUDY/Assets.xcassets/AppIcon.appiconset/512.png
  TUDY/Assets.xcassets/AppIcon.appiconset/55.png
  TUDY/Assets.xcassets/AppIcon.appiconset/57.png
  TUDY/Assets.xcassets/AppIcon.appiconset/58.png
  TUDY/Assets.xcassets/AppIcon.appiconset/60.png
  TUDY/Assets.xcassets/AppIcon.appiconset/64.png
  TUDY/Assets.xcassets/AppIcon.appiconset/72.png
  TUDY/Assets.xcassets/AppIcon.appiconset/76.png
  TUDY/Assets.xcassets/AppIcon.appiconset/80.png
  TUDY/Assets.xcassets/AppIcon.appiconset/87.png
  TUDY/Assets.xcassets/AppIcon.appiconset/88.png
  TUDY/Info.plist
  TUDY/Presentations/Chat/ViewController/PersonalChatViewController.swift
  TUDY/Repositories/FirestoreChat.swift
Labels: bug, feature, 🐶 호진

#121 홈화면 컬렉션뷰 오류 수정
  TUDY/Presentations/Home/View/BottomSheetCell.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
Labels: bug, 🐻‍❄️ 늘이
