Repository Tudy-Project/TUDY, pull requests merged in 2022-07, with the labels that each got.

#123 빠른검색 결과창
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Home/ViewController/FastSearchViewController.swift
  TUDY/Presentations/Home/ViewController/HomeViewController.swift
  TUDY/Repositories/FirebaseProject.swift
  TUDY/Util/Coordinator/Home/HomeCoordinator.swift
  TUDY/Util/Coordinator/Home/HomeCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이

#124 개인채팅 -> 그룹채팅 이동 (초대)
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이

#126 푸시알림 FCM 토큰 저장 추가
  Podfile
  Podfile.lock
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/FCMToken.swift
  TUDY/Presentations/Signup/TUDY/Presentations/Signup/ViewController/SetSubwayViewController.swift
  TUDY/Repositories/FirebaseFCMToken.swift
  TUDY/Resource/AppDelegate.swift
  TUDY/TUDY.entitlements
Labels: feature, 🐻‍❄️ 늘이

#127 토큰 가져오기
  TUDY.xcodeproj/project.pbxproj
  TUDY/Presentations/Login/ViewController/LoginViewController.swift
  TUDY/Repositories/FCMDataManager.swift
  TUDY/Repositories/FirebaseFCMToken.swift
  TUDY/Repositories/SubwayDataManager.swift
Labels: feature, 🐻‍❄️ 늘이

#129 푸시알림 FCM RestAPI 전송 (테스트 필요)
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/MessageRequest.swift
  TUDY/Models/NotificationInfo.swift
  TUDY/Repositories/FCMDataManager.swift
  TUDY/Resource/AppDelegate.swift
  TUDY/Util/Error/NetworkError.swift
Labels: feature, 🐻‍❄️ 늘이

#130 키보드 관련 성공 및 실패
  TUDY/Presentations/Chat/View/MessageCell.swift
  TUDY/Presentations/Chat/View/NewCustomInputAccessoryView.swift
  TUDY/Presentations/Chat/ViewController/NewPersonalChatVIewController.swift
  TUDY/Repositories/FirestoreChat.swift
  TUDY/Resource/AppDelegate.swift
Labels: bug, 🐶 호진

#132 [Feat] First Approach GroupChat
  TUDY/Info.plist
  TUDY/Presentations/Chat/ViewController/GroupChatViewController.swift
Labels: chore

#133 푸 시알림 오류 해결
  TUDY.xcodeproj/project.pbxproj
  TUDY/Models/MessageRequest.swift
  TUDY/Models/PushNotifiaction.swift
  TUDY/Repositories/FCMDataManager.swift
Labels: feature, 🐻‍❄️ 늘이

#135 [개인채팅창] 메세지 보낼 시, 알림
  TUDY/Presentations/Chat/ViewController/NewPersonalChatVIewController.swift
Labels: feature, 🐶 호진

#137 푸시알림 클릭 시 채팅방 이동
  TUDY/Presentations/ChatList/ViewController/ChatListViewController.swift
  TUDY/Resource/AppDelegate.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinator.swift
  TUDY/Util/Coordinator/Chat/ChatCoordinatorProtocol.swift
  TUDY/Util/Coordinator/Tap/TabCoordinator.swift
  TUDY/Util/Coordinator/Tap/TabCoordinatorProtocol.swift
Labels: feature, 🐻‍❄️ 늘이
